"""
schemas/chat.py
---------------
Pydantic request and response schemas for the /chat (AI Tutor) endpoints.

Schema Responsibilities
-----------------------
ChatQueryRequest  -- Validates the JSON body for POST /chat/query and
                     POST /chat/course/:id. Carries the student's question
                     and optional scoping filters.
SourceSnippet     -- Represents a single retrieved chunk from ChromaDB,
                     surfaced as a citation in the AI Tutor response.
ChatQueryResponse -- Wraps the LLM-generated answer together with the
                     list of source snippets used to construct it.

RAG Scoping
-----------
`course_id` and `chapter_id` are optional filters that narrow the
ChromaDB similarity search to documents belonging to a specific course
or chapter. When both are omitted, the search spans the entire
knowledge base. When `chapter_id` is provided but returns no results,
the service automatically falls back to the parent course scope.

`top_k` controls how many document chunks are retrieved from ChromaDB
before being assembled into the LLM prompt context. Defaults to 4,
which balances context quality against prompt length.
"""

from pydantic import BaseModel
from typing import Optional, List


class ChatQueryRequest(BaseModel):
    """
    Request body for POST /chat/query and POST /chat/course/:id.

    The `question` field is stripped and validated as non-empty at
    the route layer before being forwarded to the RAG pipeline.
    """

    # The student's natural-language question, sent to the LLM as-is.
    question: str

    # Optional course scope. When provided, retrieval is limited to
    # chunks belonging to this course's uploaded resources.
    course_id: Optional[int] = None

    # Optional chapter scope. Takes precedence over course_id when both
    # are supplied. Falls back to course-level scope if no chunks match.
    chapter_id: Optional[int] = None

    # Number of document chunks to retrieve from ChromaDB per query.
    # A higher value provides richer context but increases prompt length.
    top_k: Optional[int] = 4


class SourceSnippet(BaseModel):
    """
    A single retrieved document chunk returned alongside the AI answer.

    Displayed in the student UI as a citation so students can trace
    answers back to the original uploaded study material.
    """

    # Title of the resource document the chunk was extracted from.
    title: str

    # Database ID of the parent Resource record, for deep-linking.
    resource_id: Optional[int] = None

    # Database ID of the parent Chapter, for navigating the student
    # to the relevant chapter within the course.
    chapter_id: Optional[int] = None

    # First 150 characters of the retrieved chunk, shown as a preview.
    chunk_snippet: str


class ChatQueryResponse(BaseModel):
    """
    Serialised response returned by both AI Tutor query endpoints.

    `answer` is the full LLM-generated response text.
    `sources` is an ordered list of ChromaDB chunks used to construct
    the answer, enabling attribution and further reading.
    """

    # The complete answer generated by the local Ollama LLM.
    answer: str

    # Retrieved chunks used as context. Empty list when no relevant
    # study materials were found in the knowledge base.
    sources: List[SourceSnippet]
